services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: pgdb
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    container_name: elec_pred_db
    ports:
      - 5435:5432

volumes:
  postgres_volume:
