# Generated by Django 5.1.1 on 2024-10-09 23:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
