# Generated by Django 5.1.1 on 2024-10-01 19:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('question_text', models.CharField(max_length=200)),
                (
                    'pub_date',
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name='Дата публикации',
                    ),
                ),
                (
                    'start_date',
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name='Дата начала',
                    ),
                ),
                (
                    'end_date',
                    models.DateTimeField(verbose_name='Дата окончания'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Создано'
                    ),
                ),
                (
                    'question',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='votes.question',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'choice',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='votes.choice',
                    ),
                ),
                (
                    'question',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='votes.question',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'unique_together': {('user', 'choice')},
            },
        ),
    ]
