# Generated by Django 4.2.16 on 2024-10-02 12:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
