# Generated by Django 5.1.1 on 2024-10-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('votes', '0002_remove_choice_created_at_remove_choice_votes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='choice',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
