# Generated by Django 5.1.1 on 2024-10-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'votes',
            '0003_alter_question_options_remove_question_pub_date_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
