# Generated by Django 5.1.1 on 2024-10-09 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('votes', '0004_alter_choice_created_at_alter_question_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Выбор', 'verbose_name_plural': 'Выборы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Голосование',
                'verbose_name_plural': 'Голосования',
            },
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(
                max_length=200, verbose_name='Текст Выбора'
            ),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='votes.question',
                verbose_name='Голосование',
            ),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(
                max_length=200, verbose_name='Текст голосования'
            ),
        ),
    ]
