# Generated by Django 5.1.1 on 2024-10-10 00:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('votes', '0006_vote_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Голос', 'verbose_name_plural': 'Голоса'},
        ),
    ]
