# Generated by Django 5.1.1 on 2024-10-10 00:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('votes', '0007_alter_vote_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
    ]
